# Change these first
owner: fjtraindriver # Your GitHub organization or username, where this repository lives
repo: all-status # The name of this repository

sites:
  - name: CLI Proxy API
    url: $SITE_CPA
    method: GET
  - name: New-API
    url: $SITE_NEW_API
    method: GET
  - name: Vaultwarden Service
    url: $SITE_PWD
    method: GET
  - name: Brintools API Service
    url: $SITE_BTS_API
    method: GET
  - name: XPay管理后台
    url: $SITE_XPAY_ADMIN
    method: GET
  - name: XPay Payin
    url: $SITE_XPAY_PAYIN
    method: GET
  - name: XPay Payout
    url: $SITE_XPAY_PAYOUT
    method: GET

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /all-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Service Monitor" 
  introTitle: "**系统服务实时监控**"
  introMessage: "m.imtd.top"
  navbar:
    - title: "Home"
      href: /all-status

  theme: "auto"

  customCSS: |
    footer { text-align: center; padding: 3rem 0; opacity: 0.5; font-size: 0.8rem; }
    footer a { color: inherit !important; text-decoration: underline; }
    .repo-link { display: none !important; }

i18n:
  footer: "Copyright © 2026 M.IMTD.TOP. All rights reserved."
